// flow-typed signature: 865fee4a35fa5f1fcad7538ed8d2ed0d
// flow-typed version: <<STUB>>/npm-install-webpack2-plugin_v^5.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-install-webpack2-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-install-webpack2-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-install-webpack2-plugin/src/installer' {
  declare module.exports: any;
}

declare module 'npm-install-webpack2-plugin/src/plugin' {
  declare module.exports: any;
}

declare module 'npm-install-webpack2-plugin/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-install-webpack2-plugin/index' {
  declare module.exports: $Exports<'npm-install-webpack2-plugin'>;
}
declare module 'npm-install-webpack2-plugin/index.js' {
  declare module.exports: $Exports<'npm-install-webpack2-plugin'>;
}
declare module 'npm-install-webpack2-plugin/src/installer.js' {
  declare module.exports: $Exports<'npm-install-webpack2-plugin/src/installer'>;
}
declare module 'npm-install-webpack2-plugin/src/plugin.js' {
  declare module.exports: $Exports<'npm-install-webpack2-plugin/src/plugin'>;
}
declare module 'npm-install-webpack2-plugin/src/utils.js' {
  declare module.exports: $Exports<'npm-install-webpack2-plugin/src/utils'>;
}
